export const adminMenu = [
  { href: "/dashboard", title: "Дашборд", icon: "▦" },
  { href: "/integrations", title: "Интеграция AI", icon: "◎" },
  { href: "/agents", title: "Агенты", icon: "◉" },
  { href: "/knowledge", title: "База знаний", icon: "⌘" },
  { href: "/assistants", title: "Ассистенты", icon: "◈" },
  { href: "/dialogs", title: "Диалоги", icon: "◌" },
  { href: "/api-keys", title: "API ключи", icon: "◍" },
  { href: "/leads", title: "Лиды", icon: "◐" },
  { href: "/telegram-bot", title: "Telegram Bot", icon: "✈" },
  { href: "/analytics", title: "Аналитика", icon: "◔" },
  { href: "/usage", title: "Usage", icon: "◒" },
  { href: "/settings", title: "Настройки", icon: "⚙" },
  { href: "/avito", title: "Авито", icon: "◕" },
] as const;
